FROM oven/bun:latest

WORKDIR /app
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}

COPY ./apps/frontend/ ./apps/frontend
COPY ./packages/ ./packages
COPY package* .
COPY turbo.json .
COPY bun.lock .

RUN bun install
RUN bun run build

EXPOSE 3000

CMD ["bun", "run", "frontend:prod"]