FROM oven/bun:latest

WORKDIR /app

COPY ./apps/ws-relayer/ ./apps/ws-relayer
COPY ./packages/ ./packages
COPY package* .
COPY turbo.json .
COPY bun.lock .

RUN bun install
RUN bun run db:generate

EXPOSE 9093

CMD ["bun", "run", "ws-relayer"]