FROM oven/bun:latest

WORKDIR /app

COPY ./apps/web/ ./apps/web
COPY ./packages/ ./packages
COPY package* .
COPY turbo.json .
COPY bun.lock .

RUN bun install

EXPOSE 3000

CMD ["bun", "run", "frontend"]