FROM oven/bun:latest

WORKDIR /app

COPY ./apps/k8s-orchestrator/ ./apps/k8s-orchestrator
COPY ./packages/ ./packages
COPY package* .
COPY turbo.json .
COPY bun.lock .

RUN bun install
RUN bun run db:generate

EXPOSE 7000

CMD ["bun", "run", "k8s:orchestrator"]