FROM oven/bun:latest

WORKDIR /app

COPY ./apps/backend/ ./apps/backend
COPY ./packages/ ./packages
COPY package* .
COPY turbo.json .
COPY bun.lock .

RUN bun install
RUN bun run db:generate

EXPOSE 9090

CMD ["bun", "run", "primary-backend"]