FROM oven/bun:latest

WORKDIR /app

COPY ./apps/worker/ ./apps/worker
COPY ./packages/ ./packages
COPY package* .
COPY turbo.json .
COPY bun.lock .

RUN bun install
RUN bun run db:generate

EXPOSE 9091

CMD ["bun", "run", "worker"]